name: Release Golang CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-darwin-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build Darwin ARM64
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          CODE_GIT_HASH=$(git rev-parse --short HEAD)
          CODE_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LDFLAGS=-ldflags "-X main.Version=$(CODE_VERSION) -X main.GitHash=$(CODE_GIT_HASH)"
          go build $(LDFLAGS) -o dist/kdb-darwin-arm64 .
          chmod +x dist/kdb-darwin-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: kdb-darwin-arm64
          path: dist/kdb-darwin-arm64

  release:
    needs: build-darwin-arm64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Retrieve built artifact
        uses: actions/download-artifact@v4
        with:
          name: kdb-darwin-arm64
          path: dist
      - name: Generate checksum
        run: |
          cd dist
          sha256sum kdb-darwin-arm64 > kdb-darwin-arm64.sha256
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.RELEASE_VERSION }} \
            --title "Release ${{ env.RELEASE_VERSION }}" \
            --draft \
            --generate-notes
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.RELEASE_VERSION }} \
            dist/kdb-darwin-arm64 \
            dist/kdb-darwin-arm64.sha256 \
            --clobber